### ISSUE TITLE
Getting it to work in a demo...

### ISSUE THREAD

**Issue by lesv** [dannymcgee/ngx-monaco-editor#1]
Continuing on from atularen/ngx-monaco-editor#79   I'm using Angular 6.1.10.

I tried building w/ **./scripts/build-release**

And installed with: 
`npm install ~/github/ngx-monaco-editor-dannymcgee/deploy/platform/editor --save`

and when I ran I got:

`ERROR in node_modules/ngx-monaco-editor/types.d.ts(1,22): error TS6053: File '/Users/lesv/WebstormProjects/src/platform/editor/monaco.d.ts' not found.`

Is there a better way to build this?  I started to try your suggestion of copying the files into my project, but realized that I'd have OSS issues that I wasn't ready to figure out if I did that.

**Comment by dannymcgee** [comment]
You need to add the glob to your assets array in angular.json as described in the readme, and then either run `ng build` to do the copy operation, or just copy and paste the directory into your assets folder manually. I think the angular.json structure has changed since the readme was written, but in my project it goes under projects > danny-mcgee > targets > build > options > assets. Just add it to the end of the array, like this:

```
"assets": [
  "src/favicon.ico",
  "src/assets",
  {
    "glob": "**/*",
    "input": "node_modules/ngx-monaco-editor/assets/monaco",
    "output": "src/assets/monaco"
  }
]
```

**Comment by lesv** [comment]
Sigh / Thanks - I had that in most of my tests, missed it this time.  Still doesn't work, but will try to figure it out in the AM.

**Comment by lesv** [comment]
Actually, I did have it for "build": { "assets", but I also put it under "test": { "assets":   and it changed things.
